### ISSUE TITLE
uninitialized constant Gem::Commands::AwaitCommand::Bundler

### ISSUE THREAD

**Issue by indirect** [segiddins/rubygems-await#1]
Steps to reproduce:

```
$ gem install rubygems-await
$ gem await rubygems-await:0.1.0
```

Observed output:

```
❯ gem await rubygems-await:0.1.0
ERROR:  Loading command: await (NameError)
        uninitialized constant Gem::Commands::AwaitCommand::Bundler
        /Users/andre/.gem/ruby/3.2.2/gems/rubygems-await-0.1.0/lib/rubygems/commands/await_command.rb:16:in `initialize'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:240:in `new'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:240:in `load_and_instantiate'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:137:in `[]'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:209:in `find_command'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
        /Users/andre/.rubies/ruby-3.2.2/bin/gem:12:in `<main>'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `deprecated?' for nil:NilClass

    cmd.deprecation_warning if cmd.deprecated?
                                  ^^^^^^^^^^^^
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
        /Users/andre/.rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:52:in `run'
        /Users/andre/.rubies/ruby-3.2.2/bin/gem:12:in `<main>'
```

<details><summary>`gem env`</summary>
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.20
  - RUBY VERSION: 3.2.2 (2023-03-30 patchlevel 53) [arm64-darwin22]
  - INSTALLATION DIRECTORY: /Users/andre/.gem/ruby/3.2.2
  - USER INSTALLATION DIRECTORY: /Users/andre/.gem/ruby/3.2.0
  - RUBY EXECUTABLE: /Users/andre/.rubies/ruby-3.2.2/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/andre/.gem/ruby/3.2.2/bin
  - SPEC CACHE DIRECTORY: /Users/andre/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/andre/.rubies/ruby-3.2.2/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-22
  - GEM PATHS:
     - /Users/andre/.gem/ruby/3.2.2
     - /Users/andre/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/andre/.gem/ruby/3.2.2/bin
     - /Users/andre/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/bin
     - /Users/andre/.rubies/ruby-3.2.2/bin
     - /Users/andre/.nodenv/shims
     - /Users/andre/.local/bin
     - /Users/andre/.bin
     - /Users/andre/.cargo/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /Users/andre/.orbstack/bin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/VMware Fusion.app/Contents/Public
     - /Library/Apple/usr/bin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /Applications/kitty.app/Contents/MacOS
     - /Users/andre/.zsh/znap/fzf-zsh-plugin/bin
     - /Users/andre/.fzf/bin
```
</details>

<details><summary>`gem list`</summary>
```
abbrev (default: 0.1.1)
actioncable (7.0.6)
actionmailbox (7.0.6)
actionmailer (7.0.6)
actionpack (7.0.6)
actiontext (7.0.6)
actionview (7.0.6)
activejob (7.0.6)
activemodel (7.0.6)
activerecord (7.0.6)
activestorage (7.0.6)
activesupport (7.0.6)
acts_as_tenant (0.6.1)
addressable (2.8.4)
administrate-field-active_storage (0.4.2)
aes_key_wrap (1.1.0)
algoliasearch (1.27.5)
ansi (1.5.0)
arask (1.2.6)
ast (2.4.2)
async (2.6.2)
async-http (0.60.2)
async-io (1.35.0)
async-pool (0.4.0)
async-websocket (0.25.1)
atomos (0.1.3)
attr_required (1.0.1)
base64 (default: 0.1.1)
bcrypt (3.1.18)
benchmark (default: 0.2.1)
better_html (2.0.1)
bigdecimal (default: 3.1.3)
bindata (2.4.15)
bindex (0.8.1)
bootsnap (1.16.0)
brakeman (6.0.1)
builder (3.2.4)
bundler (2.4.20, 2.4.19, 2.4.18, 2.4.17, 2.4.13, 2.3.11)
bundler-audit (0.9.1)
byebug (11.1.3)
capybara (3.39.2)
CFPropertyList (3.0.6)
cgi (default: 0.3.6)
childprocess (4.1.0)
chronic (0.10.2)
chunky_png (1.4.0)
claide (1.1.0)
cocoapods (1.12.1)
cocoapods-core (1.12.1)
cocoapods-deintegrate (1.0.5)
cocoapods-downloader (1.6.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.1)
cocoapods-trunk (1.6.0)
cocoapods-try (1.2.0)
coderay (1.1.3)
colored2 (3.1.2)
concurrent-ruby (1.2.2)
connection_pool (2.4.1)
console (1.18.0)
countries (5.4.0)
country_select (8.0.1)
crack (0.4.5)
crass (1.0.6)
cssbundling-rails (1.2.0)
csv (default: 3.2.6)
date (default: 3.3.3)
debug (1.8.0, 1.7.1)
delegate (default: 0.3.0)
devise (4.9.2)
devise-i18n (1.11.0)
did_you_mean (default: 1.6.3)
diff-lcs (1.5.0)
digest (default: 3.1.1)
dockerfile-rails (1.5.2, 1.5.1)
domain_name (0.5.20190701)
drb (default: 2.1.1)
english (default: 0.7.2)
erb (default: 4.0.2)
erb_lint (0.4.0)
error_highlight (default: 0.5.1)
erubi (1.12.0)
escape (0.0.4)
et-orbi (1.2.7)
etc (default: 1.4.2)
ethon (0.16.0)
faraday (2.7.10, 1.10.1)
faraday-em_http (1.0.0)
faraday-em_synchrony (1.0.0)
faraday-excon (1.1.0)
faraday-follow_redirects (0.3.0)
faraday-httpclient (1.0.1)
faraday-mashify (0.1.1)
faraday-multipart (1.0.4)
faraday-net_http (3.0.2, 1.0.1)
faraday-net_http_persistent (1.2.0)
faraday-patron (1.0.0)
faraday-rack (1.0.0)
faraday-retry (1.0.3)
faraday_middleware (1.2.0)
fcntl (default: 1.0.2)
ffi (1.15.5)
ffi-compiler (1.0.1)
fiber-annotation (0.2.0)
fiber-local (1.0.0)
fiddle (default: 1.1.1)
fileutils (default: 1.7.0)
find (default: 0.1.1)
formatador (1.1.0)
forwardable (default: 1.3.3)
fourflusher (2.3.1)
fugit (1.8.1)
fuzzy_match (2.0.4)
getoptlong (default: 0.2.0)
gh_inspector (1.1.3)
gli (2.21.1)
globalid (1.1.0)
guard (2.18.0)
guard-brakeman (0.8.6)
guard-bundler-audit (0.1.5)
guard-compat (1.2.1)
guard-erb_lint (1.0.1)
guard-minitest (2.4.6)
guard-rspec (4.7.3)
guard-rubocop (1.5.0)
guard-shell (0.7.2)
hashdiff (1.0.1)
hashids (1.0.6)
hashie (5.0.0)
honeybadger (5.2.1)
hookup (1.2.5)
hotwire-livereload (1.2.3)
http (5.1.1)
http-cookie (1.0.5)
http-form_data (2.3.0)
httpclient (2.8.3)
i18n (1.14.1)
ice_cube (0.16.4)
image_processing (1.12.2)
iniparse (1.5.0)
inline_svg (1.9.0)
invisible_captcha (2.1.0)
io-console (default: 0.6.0)
io-event (1.2.2)
io-nonblock (default: 0.2.0)
io-wait (default: 0.3.0)
ipaddr (default: 1.2.5)
irb (1.7.4, default: 1.6.2)
jquery-rails (4.5.1)
jsbundling-rails (1.1.2)
json (default: 2.6.3, 2.6.2)
json-jwt (1.16.3)
kaminari (1.2.2)
kaminari-actionview (1.2.2)
kaminari-activerecord (1.2.2)
kaminari-core (1.2.2)
language_server-protocol (3.17.0.3)
launchy (2.5.2)
letter_opener (1.8.1)
letter_opener_web (2.0.0)
lint_roller (1.1.0)
listen (3.8.0)
llhttp-ffi (0.4.0)
local_time (2.1.0)
logger (default: 1.5.3)
loofah (2.21.3)
lumberjack (1.2.8)
mail (2.8.1)
marcel (1.0.2)
matrix (0.4.2)
method_source (1.0.0)
mime-types (3.4.1)
mime-types-data (3.2022.0105)
mini_magick (4.12.0)
mini_mime (1.1.2)
minitest (5.18.1, 5.16.3)
molinillo (0.8.0)
msgpack (1.7.1)
multipart-post (2.3.0, 2.2.3)
mutex_m (default: 0.1.2)
name_of_person (1.1.1)
nanaimo (0.3.0)
nap (1.1.0)
nenv (0.3.0)
net-ftp (0.2.0)
net-http (default: 0.3.2)
net-imap (0.3.6, 0.3.4)
net-pop (0.1.2)
net-protocol (default: 0.2.1)
net-smtp (0.3.3)
netrc (0.11.0)
nio4r (2.5.9)
nkf (default: 0.1.2)
nokogiri (1.15.3 arm64-darwin, 1.15.2 arm64-darwin)
noticed (1.6.3)
notiffany (0.1.3)
oauth (0.5.10)
observer (default: 0.1.1)
oga (3.4)
oj (3.15.0)
omniauth (2.1.1)
omniauth-rails_csrf_protection (1.0.1)
omniauth_openid_connect (0.7.1)
open-uri (default: 0.3.0)
open3 (default: 0.1.2)
openid_connect (2.2.0)
openssl (default: 3.1.0)
optparse (default: 0.3.1)
orm_adapter (0.5.0)
ostruct (default: 0.5.5)
overcommit (0.60.0)
pagy (6.0.4)
parallel (1.23.0)
parser (3.2.2.3)
pathname (default: 0.2.1)
pay (6.7.0)
pdf-core (0.9.0)
pg (1.5.3)
pg_search (2.3.6)
power_assert (2.0.3)
pp (default: 0.4.0)
prawn-table (0.2.2)
prefixed_ids (1.6.0)
pretender (0.5.0)
prettier_print (1.2.1)
prettyprint (default: 0.1.1)
prime (0.1.2)
protocol-hpack (1.4.2)
protocol-http (0.24.4)
protocol-http1 (0.15.0)
protocol-http2 (0.15.1)
protocol-rack (0.2.6)
protocol-websocket (0.12.0)
pry (0.14.2)
pry-byebug (3.10.1)
pry-doc (1.4.0)
pry-rails (0.3.9)
pstore (default: 0.1.2)
psych (default: 5.0.1)
public_suffix (5.0.1, 4.0.7)
puma (6.3.0)
pundit (2.3.1)
raabro (1.4.0)
racc (1.7.1, default: 1.6.2)
rack (2.2.7)
rack-oauth2 (2.2.0)
rack-protection (3.0.6)
rack-test (2.1.0)
rails (7.0.6)
rails-dom-testing (2.1.1)
rails-html-sanitizer (1.6.0)
railties (7.0.6)
rainbow (3.1.1)
rake (13.0.6)
rb-fsevent (0.11.2)
rb-inotify (0.10.1)
rbs (2.8.2)
rdoc (default: 6.5.0)
readline (default: 0.0.3)
readline-ext (default: 0.1.5)
receipts (2.2.0)
redis (5.0.6)
redis-client (0.14.1)
regexp_parser (2.8.1)
reline (0.3.6, default: 0.3.2)
request_store (1.5.1)
resolv (default: 0.2.2)
resolv-replace (default: 0.1.1)
responders (3.1.0)
rexml (3.2.5)
rinda (default: 0.1.1)
rotp (6.2.2)
rqrcode (2.2.0)
rqrcode_core (1.2.0)
rspec (3.12.0)
rspec-core (3.12.2)
rspec-expectations (3.12.3)
rspec-mocks (3.12.5)
rspec-rails (6.0.3)
rspec-support (3.12.0)
rss (0.2.9)
rubocop (1.52.1)
rubocop-ast (1.29.0)
rubocop-capybara (2.18.0)
rubocop-factory_bot (2.23.1)
rubocop-gemfile (0.1.0.beta3)
rubocop-performance (1.18.0)
rubocop-rails (2.20.2)
rubocop-rspec (2.22.0)
ruby-ll (2.1.3)
ruby-lsp (0.10.1, 0.8.0, 0.7.4)
ruby-macho (2.5.1)
ruby-oembed (0.16.1)
ruby-progressbar (1.13.0)
ruby-vips (2.1.4)
ruby2_keywords (default: 0.0.5)
rubygems-await (0.1.0)
rubygems-update (3.4.20, 3.4.19, 3.4.18)
rubyzip (2.3.2)
sassc (2.4.0)
sassc-rails (2.1.2)
schedulable (0.0.10)
securerandom (default: 0.2.2)
selectize-rails (0.12.6)
selenium-webdriver (4.10.0)
set (default: 1.0.3)
shellany (0.0.1)
shellwords (default: 0.1.0)
simple_oauth (0.3.1)
singleton (default: 0.1.1)
slack-ruby-client (2.1.0)
smart_properties (1.17.0)
smile-xml (1.0.3 java)
sorbet-runtime (0.5.10932)
sprockets (4.2.0)
sprockets-rails (3.4.2)
standard (1.30.1)
standard-custom (1.0.1)
standard-performance (1.1.1)
statesman (10.2.2)
stimulus-rails (1.2.1)
stringio (default: 3.0.4)
stripe (8.5.0)
strscan (default: 3.0.5)
swd (2.0.2)
syntax_suggest (default: 1.0.2)
syntax_tree (6.1.1)
syslog (default: 0.1.1)
tempfile (default: 0.1.3)
test-unit (3.5.7)
thor (1.2.2)
tilt (2.1.0)
time (default: 0.2.2)
timeout (0.4.0, default: 0.3.1)
timers (4.3.5)
tmpdir (default: 0.1.3)
traces (0.11.1)
tsort (default: 0.1.1)
ttfunk (1.7.0)
turbo-rails (1.4.0)
typeprof (0.21.3)
typhoeus (1.4.0)
tzinfo (2.0.6)
tzinfo-data (1.2023.3)
un (default: 0.2.1)
unaccent (0.4.0)
unf (0.1.4)
unf_ext (0.0.8.2)
unicode-display_width (2.4.2)
uri (default: 0.12.1)
validate_email (0.1.6)
validate_url (1.0.15)
vcr (6.2.0)
warden (1.2.9)
weakref (default: 0.1.2)
web-console (4.2.0)
webdrivers (5.2.0)
webfinger (2.1.2)
webmock (3.18.1)
websocket (1.2.9)
websocket-driver (0.7.5)
websocket-extensions (0.1.5)
whenever (1.0.0)
xcodeproj (1.22.0)
xpath (3.2.0)
yaml (default: 0.2.1)
yard (0.9.34)
yarp (0.11.0)
zeitwerk (2.6.9, 2.6.8)
zlib (default: 3.0.0)
```
</details>

**Comment by indirect** [comment]
Fixed in 0.1.1, thanks!
