### ISSUE TITLE
Broken with GitHub actions current default version of ruby and/or Bundler

### ISSUE THREAD

**Issue by nevans** [segiddins/rubygems-await#44]
I see an infinite (until timeout) loop of:
```
 2024-06-16 14:09:56 +0000 W [      info] [NoMethodError] /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:265:in `process_element': undefined method `dependencies' for an instance of Bundler::CompactIndexClient::Cache (NoMethodError)
        info = cic.instance_variable_get(:@cache).dependencies(name)
                                                 ^^^^^^^^^^^^^
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:249:in `block in process_collection'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:248:in `delete_if'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:248:in `process_collection'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:60:in `block in call'
	from <internal:kernel>:187:in `loop'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:53:in `call'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.2/lib/rubygems/await.rb:42:in `block in call'
2024-06-16 14:10:16 +0000 I [      info] missing: net-imap (net-imap-0.4.13)
```

I can verify that the gem _was_ successfully built and pushed: https://rubygems.org/gems/net-imap/versions/0.4.13

Ruby version: ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
Bundler version: "Using Bundler 2 shipped with ruby-3.3.1" (I think that was 2.5.9?)

Link to failed action: https://github.com/ruby/net-imap/actions/runs/9536527233/job/26283588269

**Comment by nevans** [comment]
I'm assuming that working around this is as simple as requesting `ruby/setup-ruby` install a specific version of rubygems/bundler.

**Comment by iMacTia** [comment]
Just hit the same issue today while attempting to [release a new version of Faraday](https://github.com/lostisland/faraday/actions/runs/9562005282/job/26357455151)

**Comment by sfnelson** [comment]
This has broken all of our private GitHub actions. Rails latest + Ruby 3.3.3.

**Comment by ccutrer** [comment]
Another failed run: https://github.com/instructure/bundler-multilock/actions/runs/9670566983/job/26679496431

**Comment by iMacTia** [comment]
OK so it seems like a [recent refactor](https://github.com/rubygems/rubygems/commit/71bcf354f5b33924d2e5b2d6190806a3ef237de9) of Bundler's internal meant the functionality provided by `@cache.dependencies` has been moved into a new `@parser` object.

Should be an easy fix with a version check, I can open a PR to give it a stub.
cc @segiddins

**Comment by iMacTia** [comment]
PR is ready: https://github.com/segiddins/rubygems-await/pull/46
