### ISSUE TITLE
Further build issues after latest bundler release

### ISSUE THREAD

**Issue by sfnelson** [segiddins/rubygems-await#47]
Similar to #44 (fixed by #46), rubygems-await is not able to detect successful releases in Github actions after the latest release of rubygems.

The await appears to start successfully, then prints a warning about a missing `rename` in fileutils.

After this, the build continues to run but never detects the successful release.

```
2024-06-28 07:16:28 +0000 W [  versions] [Errno::ENOENT] /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1169:in `rename': No such file or directory @ rb_file_s_rename - (/home/runner/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions.1920.tmp, /home/runner/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions) (Errno::ENOENT)
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1169:in `block in mv'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:2469:in `block in fu_each_src_dest'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:2485:in `fu_each_src_dest0'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:2467:in `fu_each_src_dest'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/vendor/fileutils/lib/fileutils.rb:1160:in `mv'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:139:in `block in commit'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:138:in `commit'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:123:in `commit!'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:118:in `write'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:43:in `block in write'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:55:in `initialize'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:41:in `new'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache_file.rb:41:in `write'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/updater.rb:55:in `replace'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/updater.rb:17:in `update'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache.rb:80:in `fetch'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/cache.rb:26:in `versions'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client/parser.rb:24:in `versions'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/bundler-2.5.14/lib/bundler/compact_index_client.rb:69:in `versions'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.3/lib/rubygems/await.rb:211:in `process_collection'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.3/lib/rubygems/await.rb:60:in `block in call'
	from <internal:kernel>:187:in `loop'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.3/lib/rubygems/await.rb:53:in `call'
	from /opt/hostedtoolcache/Ruby/3.3.3/x64/lib/ruby/gems/3.3.0/gem_exec/gems/rubygems-await-0.5.3/lib/rubygems/await.rb:42:in `block in call'
2024-06-28 07:16:29 +0000 I [  versions] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:16:33 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:16:37 +0000 I [  versions] found katalyst-tables-3.3.2
2024-06-28 07:16:37 +0000 I [  versions] all found!
2024-06-28 07:16:38 +0000 I [full index] missing: katalyst-tables-3.3.2
2024-06-28 07:16:39 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:16:48 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:16:48 +0000 I [full index] missing: katalyst-tables-3.3.2
2024-06-28 07:16:52 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:16:55 +0000 I [full index] found katalyst-tables-3.3.2
2024-06-28 07:16:56 +0000 I [full index] all found!
2024-06-28 07:17:01 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:17:07 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:17:14 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:17:22 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:17:31 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:17:41 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:17:52 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:18:04 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:18:17 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:18:31 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:18:46 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:19:02 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:19:19 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:19:37 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:19:56 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:20:16 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:20:37 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
2024-06-28 07:20:59 +0000 I [      info] missing: katalyst-tables (katalyst-tables-3.3.2)
```

See https://github.com/katalyst/tables/actions/runs/9708970325/job/26796749546 for an example.

**Comment by iMacTia** [comment]
It might be we managed to get past the issue in #44 and now we hit a new issue, but this might have been around for a while and the code just never managed to get here. I'll try taking a quick look again and see if I can track this down as well 😄

**Comment by segiddins** [comment]
Give https://github.com/segiddins/rubygems-await/pull/52 a try?

**Comment by sfnelson** [comment]
@segiddins happy to test, how do I do so? The action fails reliably.

**Comment by iMacTia** [comment]
Thank you for opening #52 @segiddins, I totally missed the checksum was also moved into the parser 🤦 
Will definitely give it a try on my next Faraday release.

@sfnelson you can test the fix in #52 using the [commit sha](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-a-commits-sha-for-release-management)

**Comment by sfnelson** [comment]
@iMacTia I'm not clear how to use that on GitHub Actions, but I've tested locally and this change does resolve my issue.

**Comment by iMacTia** [comment]
Sorry @sfnelson I forgot `rubygems-await` is used as a dependency of the `rubygems/publish-gem` action, the link I shared was not really helpful.

@segiddins I managed to give this a go just now by explicitly installing `rubygems-await` pointing to the last commit in #52. You can see the action run here: https://github.com/lostisland/faraday/actions/runs/9837249299/job/27154646226 (note the fetching from your GitHub repo in the `setup-ruby` step, I'm pointing to it from our repo Gemfile).

The release worked and I received the email correctly this time, but the action is not completing successfully and still showing the error message in the description of this issue

**Comment by segiddins** [comment]
Given it's running `gem exec`, I think it might still be using the published version. Let me try cutting a new release

**Comment by iMacTia** [comment]
mmmh it might be. When I read [the documentation](https://guides.rubygems.org/command-reference/#:~:text=The%20exec%20command%20handles%20installing,new%20.%20will%20run%20rails%20new%20.), it seemed like it would only install the gem "if needed", but there's no clear way to tell just by looking at the logs unfortunately.

Thank you for the new release, I'll let you know if I still bump into issues on the next Faraday release 👍
